---
- name: Installation X3V12
  hosts: all
  
  pre_tasks:  
    - name: Vérifie si le compte de service est admin local
      win_group_membership:
        name: Administrateurs
        members: "{{ ansible_user }}"
        state: present
      register: result

  roles:
    - role: X3V12
      when: result.failed = false
