---
- name: Installation X3V12
  hosts: all
  
  pre_tasks:  
    
    block:
      - win_group_membership:
          name: Administrateurs
          members: "{{ ansible_user }}"
          state: present
        register: result
        failed_when: result.rc != 0 and result.rc != 6

      - debug:
          var: result

    rescue:
      debug:
        msg: Le compte de service {{ ansible_user }} n'est pas administrateur

  roles:
    - role: X3V12
      when: result.rc != 0 and result.rc != 6
