---
- name: Debug playbook
  hosts: X3-2
  
  tasks:
    - name: Configure disks
      include_tasks: roles/WINDOWS/tasks/storage.yaml

    - name: win_disk_facts
      win_disk_facts:
        filter: 
          - win32_disk_drive
          - partitions

    - name: Detect disks without any partitions
      set_fact:
        no_part: "{{ ansible_facts['disks'] | json_query('[?win32_disk_drive.partitions == `0`]') }}"

    - name: Debug ansible_facts json query
      debug:
        var: no_part

    - name: Configure partitions 
      include_tasks: roles/WINDOWS/tasks/storage2.yaml
      loop: "{{ no_part }}"
