---
- name: Download ISO X3 LP 12.0.30
  win_get_url:
    url: http://193.178.211.127/kardol-inge/RCA/x3-12.0.30.iso
    dest: '%userprofile%\Downloads\x3-12.0.30.iso'
    force: no

- name: Download ISO SEED LP 12.0.30
  win_get_url:
    url: http://193.178.211.127/kardol-inge/RCA/x3-seed-12.0.30.iso
    dest: '%userprofile%\Downloads\x3-seed-12.0.30.iso'
    force: no

- name: Download and install Zulu JRE 8
  include_role:
    name: ansible-role-java