---
- name: Download ISO X3 LP 12.0.30
  win_get_url:
    url: http://193.178.211.127/kardol-inge/RCA/x3-12.0.30.iso
    dest: '%userprofile%\Downloads\x3-12.0.30.iso'
    checksum: 63a470eb7d28cde7d94b51211c3a3ef5f6fef2378bcec1278787e978f0d926d2
    checksum_algorithm: sha256
    force: no

- name: Download ISO SEED LP 12.0.30
  win_get_url:
    url: http://193.178.211.127/kardol-inge/RCA/x3-seed-12.0.30.iso
    dest: '%userprofile%\Downloads\x3-seed-12.0.30.iso'
    checksum: 9d6ead684f85a61b26b577f49e40a6477f2b3b3ed2a1f6c06b8521d55c0f5cc9
    checksum_algorithm: sha256
    force: no
  when: inventory_hostname in groups["application"]

- name: Download and install Zulu JRE 8
  include_role:
    name: JAVA

