---
- name: Installation outils
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
        - googlechrome
        - notepadplusplus

- name: Installation robo3t
  win_chocolatey:
    name: robo3t
    state: present
  when: inventory_hostname in groups["mongodb"]

- name: Règle de parefeu SageX3 activée
  win_firewall_rule:
    name: SageX3
    localport: "{{ item }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
  loop:
    "{{ x3_ports }}"

- name: Règle de parefeu SQL activée
  win_firewall_rule:
    name: SQL
    localport: 1434
    action: allow
    direction: in
    protocol: udp
    state: present
    enabled: yes

