---
- name: Installation outils
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
        - googlechrome
        - notepadplusplus

- name: Installation robo3t
  win_chocolatey:
    name: robo3t
    state: present
  when: inventory_hostname in groups["mongodb"]
