set ROBOCOPY=C:\Windows\System32\Robocopy.exe
set SOURCE=\\192.168.230.51\e$\SAGE\SAGEX3V6\FAIVELEY\Dossiers\CLFAIVELEY
set DESTINATION=E:\SAGE\SAGEX3V6\FAIVELEYV6\Dossiers\CLFAIVELEY

%ROBOCOPY% %SOURCE% %DESTINATION% /FFT /NP /MT:16 /e /w:2 /r:2 /XD %SOURCE%\TRA %SOURCE%\tmp /XF %SOURCE%\adxodbc
md %DESTINATION%\TRA
md %DESTINATION%\tmp
