---

# Set the Computername
- name: Configure the Windows hostname
  ansible.windows.win_dsc:
    resource_name: computer
    Name: "{{ inventory_hostname }}"
  register: computer_result

- name: Reboot to apply hostname settings
  ansible.windows.win_reboot:
  when: computer_result.reboot_required
