---
- name: Disk facts are populated
  win_disk_facts:
        
- name: Intitialize and update the disk to be online
  community.windows.win_initialize_disk:
    disk_number: "{{ item.number }}"
    force: no
    online: yes
  loop: "{{ ansible_facts['disks'] | json_query('[?operational_status ==`Offline`]') }}"

- name: Create windows partitions 
  block:
    - name: Partition creation
      win_partition:
        disk_number: "{{ item.number }}"
        drive_letter: auto
        partition_size: -1
      register: partition_task

    - name: Partition is formatted
      win_format:
        path: "{{ item.path }}"
        file_system: NTFS
        allocation_unit_size: 4096
      when: partition_task['changed']
    
  loop: "{{ ansible_facts['disks'] | json_query('[?win32_disk_drive.partitions == `0`]') }}"
