---
- name: Disk facts are populated
  win_disk_facts:
    filter: physical_disk
        
- name: Intitialize and update the disk to be online
  community.windows.win_initialize_disk:
    disk_number: "{{ item.number }}"
    force: no
    online: yes
  loop: "{{ ansible_facts['disks'] | json_query('[?operational_status ==`Offline`]') }}"

