---
- name: Disk facts are populated
  win_disk_facts:
        
- name: Intitialize and update the disk to be online
  community.windows.win_initialize_disk:
    disk_number: "{{ item.number }}"
    force: no
    online: yes
  loop: "{{ ansible_facts['disks'] | json_query('[?operational_status ==`Offline`]') }}"

- name: Partition creation
  win_partition:
    disk_number: "{{ item.number }}"
    drive_letter: auto
    partition_size: -1
  loop: "{{ ansible_facts['disks'] | json_query('[?win32_disk_drive.partitions == `0`]') }}"
  register: partition_task

- name: New partition is formatted
  win_format:
    drive_letter: F
    file_system: NTFS
    new_label: data
    full: true
  when: partition_task['changed']



